### ISSUE TITLE
PopCommerce not available in newly downloaded files

### ISSUE THREAD

**Issue by CarvalhoLeonardo** [moqui/PopCommerce#14]
Hi.

 I've just downloaded moqui-1.5.2-mantle-1.0.1-HiveMind-1.1.1 bundle, put the PopCommerce zip bundle on the runtime/component, and the application doesn't run.

 The data loading looks like was successful:
" - file:/hdd/home/leonardo/Documents/Projetos/Moqui/moqui/runtime/component/PopCommerce/data/PopCommerceAaaSetupData.xml
 - file:/hdd/home/leonardo/Documents/Projetos/Moqui/moqui/runtime/component/PopCommerce/data/PopCommerceAabDocumentData.xml
 - file:/hdd/home/leonardo/Documents/Projetos/Moqui/moqui/runtime/component/PopCommerce/data/PopCommerceDemoData.xml"

  And apparently it is binding:

"128      [           main] INFO  xt.ExecutionContextFactoryImpl  - Added component [PopCommerce] at [file:/Projects/moqui/runtime/component/PopCommerce]"

But trying to access it, I got this:
"183644   [ndlerThread[19]] WARN  moqui.impl.webapp.MoquiServlet  - Web Resource Not Found: Could not find subscreen or 
transition or file/content [PopcAdmin] under screen [component://webroot/screen/webroot/apps.xml] while finding url for
 path [apps, PopcAdmin] under from screen [component://webroot/screen/webroot.xml]
183644   [ndlerThread[19]] INFO  moqui.impl.webapp.MoquiServlet  - Finished request to [/apps/PopcAdmin] of content type [text/html;charset=UTF-8] in [0.011] seconds in session [c6436073b58eda0c28d15c6349129732] thread [132:RequestHandlerThread[19]]"

   What can I do to run the application ?

System Ubuntu
gradle --version
------------------------------------------------------------
Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.13.0-36-generic amd64

**Comment by jonesde** [comment]
If you get the latest code for PopCommerce you'll also need the latest code from the moqui, mantle, and HiveMind repositories. PopCommerce has many new features with dependencies on all 3 and won't run on older versions of them. I'll be doing the first release of PopCommerce in the near future with a download that includes all dependencies but for now the best thing to do is follow the instructions in the README.md file which you can see on the PopCommerce GitHub page, i.e. at:

https://github.com/moqui/PopCommerce

BTW, chances are there are more errors in the log above the one you included and for future reference those are useful in tracking down exactly what went wrong.

**Comment by CarvalhoLeonardo** [comment]
Okie dokie, getting the master files did the trick, thank you!
