### ISSUE TITLE
Unable to resolve class  org.joda.time.MutableDateTime while creating Invoice

### ISSUE THREAD

**Issue by mrovnanik** [moqui/PopCommerce#24]
After upgrading runtime and framework to the newest version, the create#Invoice service (in InvoiceServices.xml) started to return this error. It is the script provided below the error.

mantle_account_InvoiceServices_create_Invoice: 51: unable to resolve class  org.joda.time.MutableDateTime 
 @ line 51, column 21.
       def dueDateDt = new org.joda.time.MutableDateTime(invoiceDate.time...

![image](https://cloud.githubusercontent.com/assets/14863763/18481258/dfa7217e-79db-11e6-99e8-a41eaf1ba4c2.png)

**Comment by mrovnanik** [comment]
I put the joda-time-2.4.jar into runtime/lib. Is that the correct way to solve it?

**Comment by jonesde** [comment]
Do you have the latest version of mantle-usl? There was an update to mantle-usl around the same time as the moqui-framework update to get rid of Joda Time and use the new java.time classes in Java 8.

**Comment by mrovnanik** [comment]
No, I don't. I have been using my own version, since I was learning new things by experimenting. I shall have my code organized in a better fashion.
