### ISSUE TITLE
Customers and Suppliers are not visible

### ISSUE THREAD

**Issue by jenshp** [moqui/PopCommerce#25]
Currently, customers and suppliers are filtered according to the organization for which they are considered customers or suppliers (through PartyRelationship records). This works fine if there effectively are PartyRelationship records present.
However, both for the Demo data as for newly created customers and suppliers, no such records are created, so these customers and suppliers are not shown (in the respective PopcAdmin/Customer/FindCustomer and PopcAdmin/Supplier/FindSupplier screens).
Vendors are not yet filtered this way but I suppose all 3 groups would receive consistent treatment in the future.
Note: this problem is not visible when logging in with the john.doe username, unless you specifically select an active organization.

Possible solutions are either to add the respective PartyRelationship records on creation (would require to have an active organization upon creation or to select one explicitly), or to show customers/suppliers when they have no PartyRelationship records with any internal organization.

**Comment by jonesde** [comment]
The organization based filtering is all managed through configuration. There are various ways this could be improved for demo purposes, and based on this feedback I'm moving the ArtifactAuthzFilter records to the demo data file.

The PartyRelationship records for both the users and customers/suppliers/vendors/etc can be administered already, though it is a separate step from creating a user. It might make sense to add an initial organization for users and customers/suppliers/etc, that would be a good enhancement that maybe I'll get to sooner or later (unfortunately the time I have available to work on these apps is very limited so not likely I'll do it in the near future).

**Comment by jonesde** [comment]
This is an old issue and various changes have been made to improve this, so closing.
