### ISSUE TITLE
Minor Design bug

### ISSUE THREAD

**Issue by mckhoi** [moqui/PopCommerce#27]
1. http://localhost:8080/apps/PopcAdmin/Vendor/Accounting/ItemTypes?partyId=HM_AWS
2. click on "Add From Missing Item Types"

the content of the dialog box is too big.

also here
1. http://localhost:8080/apps/PopcAdmin/Vendor/Accounting/PaymentTypes?partyId=HM_AWS
2. click on "Add From Missing Payment Types"

**Comment by jonesde** [comment]
This is improved in commit #da1f3c9 in the SimpleScreens repository.
