### ISSUE TITLE
Field cannot be empty (for field partyId of service mantle.party.ContactServices.get#PartyContactInfo)

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/PopCommerce#28]
To reproduce

1. Create a sales order without customer
2. Place order 
3. You will get the error on the order part section

**Comment by jonesde** [comment]
Are you looking at the ecommerce app or the POP Commerce Admin app? Also, which version?

In the latest code for the admin app it allows creating an order without a customer but warns the user when this is the case, and for sales orders also warns about other things like no shipping address or payment settings. In these cases the place order button turns into a dialog button that shows the warnings, still allowing the user to proceed.

In this case we could not allow the order to be placed without a customer.

How would you prefer it to behave for whatever business scenario you are working on?

**Comment by zhangwei1979** [comment]
Sorry I lost a step to reproduce this issue 

1. Create a sales order without customer
2. Place order
3. Approve the order
4. You will get the error on the order part section

**Comment by jonesde** [comment]
I'm still tempted to not allow placing an order if there is no customer, but I found the errors that I think you're referring to which were in the new order emails sections and those are fixed.
