### ISSUE TITLE
Unable to login to demo application

### ISSUE THREAD

**Issue by NiteshSoni** [moqui/PopCommerce#29]
The following Error encountered after clicking on Roles-> Admin Rights. The same error repeats on clicking View Demo-> Test User David Jones.

HTTP Status 500 - Error rendering screen [component://webroot/screen/webroot.xml]
type Status report
message Error rendering screen [component://webroot/screen/webroot.xml]
description The server encountered an internal error that prevented it from fulfilling this request.
Apache Tomcat/8.0.39

Now unable to login to demo application with test user.

**Comment by jonesde** [comment]
I don't know what "Roles -> Admin Rights" or "View Demo -> Test User David Jones" are, there is nothing like those in the OOTB apps, but going to plain demo.moqui.org it looked like the servers were down. I didn't look into why, but reset the data in the database and restarted and now they are up again.

Thank you for reporting this, it does tend to happen with this open demo server where anyone can login with the admin credentials (and change things that break the apps).

**Comment by NiteshSoni** [comment]
That true. I went to demo server HiveMind Admin->Users->john.doe and clicked on "Add to Admin Group".
Now it is working fine. Thank you!
