### ISSUE TITLE
New Shipment without Order

### ISSUE THREAD

**Issue by locnguyenx** [moqui/PopCommerce#30]
I want to try create a new outgoing Shipment without Order, using following steps:
1. Create new Outgoing Shipment in screen PopcAdmin/Shipment/FindShipment
2. In ShipmentDetail screen, add new Item, i.e DEMO_1_1 with quantity = 1
3. Set Scheduled
4. Pack Item: add new package, select asset id DEMO_1_1A and submit. Error occurs: Field cannot be empty (for field orderId of service mantle.product.AssetServices.displace#AssetReservations)

I've checked and found that in service `ShipmentServices.pack#ShipmentItemSource`, because no asset reservation then  service mantle.product.AssetServices.displace#AssetReservations will be called to force clearing other reservation. However, orderId param is required in displace#AssetReservations service.

So, I wonder if this is a bug of ShipmentServices or this ShipmentDetail screen in POPC is not designed to work with an adhoc Shipment.

**Comment by jonesde** [comment]
Thanks for reporting this, though it is an issue in mantle-usl more than in PopCommerce. I made some changes to handle packing a shipment item that did not come from an order item if you specify an Asset to pack from. These changes are in commit #635eee0 in the mantle-usl repository.

One caveat to this that isn't handled automatically is charging a customer for items shipped like this. If you want to charge for them they need to be manually invoiced as there is no data on a ShipmentItem for how much to charge, etc.
