### ISSUE TITLE
Can't create Shipment after Order is completed

### ISSUE THREAD

**Issue by locnguyenx** [moqui/PopCommerce#31]
Currently, in OrderDetail screen, if Order is completed, we can't create Shipment if hasn't created it before.

I find that in mantle-udm, there's a  StatusTransitionFlow that allows Order to change status from Completed to Approved. Applying this flow, we will have a chance to create Shipment.

**Comment by jonesde** [comment]
This is actually an issue in SimpleScreens and one change to improve this is included in commit #0586a0e in that repository. It is just a simple Uncomplete button for the order. I may make other changes like allowing a shipment create or add to shipment if not all items are shipped, but this at least handles the status issue and may be useful for other things too.
