### ISSUE TITLE
EditParty screen related company

### ISSUE THREAD

**Issue by hansbak** [moqui/PopCommerce#41]
on the party edit screen (http://localhost:8080/vapps/PopcAdmin/Party/EditParty?partyId=????)
it is only possible to add a related organization if:
1. a user login account is created.
2. the user has a role of sales contact.

It should be possible for all persons in any role even without a userlogIn to enter a related organizationId.

**Comment by jonesde** [comment]
Here is the logic for the Sales Contact specific part of the screen:

https://github.com/moqui/SimpleScreens/blob/master/screen/SimpleScreens/Party/EditParty.xml#L612

Here is one of 3 sections on the screen for Sales Account:

https://github.com/moqui/SimpleScreens/blob/master/screen/SimpleScreens/Party/EditParty.xml#L648

It has nothing to do with a User Account, only with the Sales Contact and Sales Account roles.

I could see perhaps showing these for any Party with the Customer role, but they are not applicable and would just make the screen much bigger and more complex for other Parties.

**Comment by hansbak** [comment]
OK, thank you david.
