### ISSUE TITLE
New user password

### ISSUE THREAD

**Issue by hansbak** [moqui/PopCommerce#43]
When a new user is created it is possible to enter a new password and leave the 'require change password' to 'y' which is the default setting.

When however this new user is trying to login with the entered password, he is not able to, because he is notified with the message:
Authenticate failed for user [david] because account requires password change [PWDCHG].

Shouldn't the new user be able to use the entered password and be prompted for a new one?

When he presses the 'reset password' and enters his username , then he is able to enter the entered password....(?)

**Comment by jenshp** [comment]
Currently, the password sent via mail only allows to change the password, not to log in with that password. Therefore, at the login screen, you need to select the "change password" link to change the password without logging in.

**Comment by hansbak** [comment]
I am talking about the initial password when the user was created. can only use that password if the reset password is requested but not used....all a bit confusing.

**Comment by growerp** [comment]
My suggestion would be to change the default setting of 'Require Password Change' to 'N' so the new user can enter his given password without being forced to use the reset password function at the login screen. or make this setting dependent if a password was given at login creation.

**Comment by hansbak** [comment]
fine for now
