### ISSUE TITLE
Internationalization ERP app

### ISSUE THREAD

**Issue by donhuvy** [moqui/PopCommerce#50]
I want ask you about internationalization ERP app (PopCommerce). Do you accept this task? If you accept, I will take care this task. I need localization (L10N) application to Vietnamese for our customers, firstly, we need internationalization (I18N) it.

**Comment by jonesde** [comment]
The better forum for discussing things like this is the Moqui Ecosystem mailing list. For more information please see:

https://moqui.org/m/docs/moqui/Community+Guide#comments-and-discussions
