### ISSUE TITLE
Star rating component

### ISSUE THREAD

**Issue by abdullahs** [moqui/PopCommerce#9]
This is in continuation to discussion on [Issue 88](https://github.com/moqui/moqui/pull/88).

1) For resources (css/js) should I place them in PopCommerceRoot/assets/lib/rating folder same as webroot or somewhere else ?

2) Where should the schema definition go ? Do I need to create custom form xsd ? Because I think we should not be using the existing framework/xsd/xml-form-1.5.xsd as the widget resource are part of PopCommerce

3) Same as Point 3 where should the macro definition go ?

Please let me know and I will create PR accordingly. Thanks.

**Comment by jonesde** [comment]
My recommendation in the other issue was don't use a special screen/form element at all, so you don't need to add it to the schema or create a macro. Instead use a render-mode.text element in the page where the rating widget is used, basically containing what the macro would contain.

The "assets" directory is really a Metis thing, and only used in webroot to use a directory structure that more or less mirrors the Metis one. I'd recommend using something more simple/generic like "static/rating" for the css and js files for the rating widget.
